title: Intermediate concepts for Python
email: git@xoolive.org
description: >- # this means to ignore newlines until "baseurl:"
  Materials to brush up your Python skills
github_username: xoolive
repository: xoolive/pyseminar
logo: imgs/python.png
theme: jekyll-theme-minimal

exclude:
  - .mypy_cache
